### ISSUE TITLE
Purchasing SmartThings

### ISSUE THREAD

**Issue by ezoehunt** [mozilla/connected-devices-experiments#1]
This is a diary-like review of the process of purchasing SmartThings. It's meant to observe the end-to-end consumer experience of investigating and then purchasing SmartThings. So it goes beyond a standard UX heuristic review of the SmartThings website to include my questions, thoughts, observations, and feelings during the process. 

I'll continue it in another issue once I receive the SmartThings products.

Feel free to comment - especially if you've also purchased anything in the SmartThings family!

++++++++++++++++++++
**Table of Contents**
**[Context](https://github.com/mozilla/connected-devices-experiments/issues/1#context)**
**[Research](https://github.com/mozilla/connected-devices-experiments/issues/1#research)**
**[Add to Cart](https://github.com/mozilla/connected-devices-experiments/issues/1#addcart)**
**[Purchase](https://github.com/mozilla/connected-devices-experiments/issues/1#purchase)**
**[I want more fun!](https://github.com/mozilla/connected-devices-experiments/issues/1#fun)**
++++++++++++++++++++
### <a name="context"></a>Context

I'm buying some SmartThings items to test out the system. Because we've been looking into the smart home industry, I'd already reviewed the SmartThings website. Based on my earlier reviews, I thought that SmartThings was focused on lighting, security, and monitoring the home. 

But Valerie C explained that SmartThings can do a lot more than I thought it could do. I want to test that with two scenarios: 1) automating my morning routine (coffee, lights, music), and 2) learning when my mail arrives -- the mailbox is a short walk from my house, and I want to know the mail is there before I walk down.
++++++++++++++++++++
### <a name="research"></a>Research

_Thursday, Feb 11, 2016_
I've already decided to buy SmartThings. So I'm not looking for comparisons with other smart home tech or for consumer reviews. Since my scenarios are fairly specific, I'm looking for information that will help me figure out what I need to buy to bring these scenarios to life. 

So I visit the SmartThings website. 

<img width="1054" alt="st_home" src="https://cloud.githubusercontent.com/assets/234670/13094711/6826f5f8-d4c1-11e5-8640-b49f606172df.png">

Hmm, _monitor_, _control_, and _secure_ are words that make me think SmartThings is only about security and monitoring systems. This doesn't sound promising since I’m looking to do very different things in my home.

I already know I need to buy a hub and some "things" for my scenarios. I'm a fairly regular home DIY-er, so I'm comfortable finding someone else’s idea and tweaking it for my own purposes. I want examples of things other people have done with their SmartThings system. I would love to find my exact scenarios with a step-by-step tutorial and just click "buy all" and be done with it. I realize this is a farfetched request -- it would be impossible for SmartThings to anticipate every scenario for every consumer. But there's probably some often repeated ones, like morning routine...

A couple scrolls down the homepage is a link to _Explore Uses_ -- I click that.

<img width="1048" alt="st_explore_uses" src="https://cloud.githubusercontent.com/assets/234670/13094762/c4a993c6-d4c1-11e5-8de1-ea370690607e.png">

I'm not sure what to click on this page. Morning routine stuff is probably under _Convenience and Entertainment_, but where would "know when mail has arrived" be? I start by clicking _Convenience and Entertainment_.

<img width="1051" alt="st_c_and_e" src="https://cloud.githubusercontent.com/assets/234670/13094792/fd149c74-d4c1-11e5-9ffc-669033f5cefb.png">

In the "James" section of _Convenience and Entertainment_, I click _See his apartment_ to learn about his morning routine setup. 

<img width="1051" alt="st_james" src="https://cloud.githubusercontent.com/assets/234670/13094864/65cdacb0-d4c2-11e5-8c15-2d13a29cefca.png">

I watch the video. It sounds similar to my morning routine scenario. I'm hoping I can just copy and tweak his setup! I scroll down to see the "things" James used to create his setup. Wow, 12 pieces of hardware...sounds complicated.

<img width="1050" alt="st_james_buy" src="https://cloud.githubusercontent.com/assets/234670/13094881/8684d866-d4c2-11e5-9ae3-f8a2ad682b7a.png">

Scroll further to read how he set it up. Ugh, it's like SmartThings is not even trying to make this easy for me. 

<img width="1053" alt="st_james_do" src="https://cloud.githubusercontent.com/assets/234670/13094906/a9326f68-d4c2-11e5-9293-cb7dd0b959c2.png">

The description of how to "do this at home" is too vague for me to feel confident I could re-create it. So it fails as an explicit "do this at home" tutorial. Yet there's so much description that it also fails as a "hey anybody can build this" message. I walk away thinking that re-creating this will be tedious, boring, complex, and expensive. 

I’ve lost the motivation to continue this research today.
++++++++++++++++++++
### <a name="addcart"></a>Add to Cart

_Friday, Feb 12, 2016_
Motivated again! All the "things" need a hub, so I go to _Shop_ and add a hub to my cart. What else do I need to buy? 

When I wake up, I want the system to turn on the kitchen lights and the coffeepot and turn on either NPR or my favorite jazz station. The time I wake up varies from day to day, so I can't set these up on a schedule. What can I use as a trigger?

A weight sensor seems to make sense. When the bed detects less weight, that triggers the other actions. I look around in the SmartThings product area, but don’t see anything about weight.

I google "smartthings and weight sensor." I find [this forum](https://community.smartthings.com/t/weight-sensor-load-sensor-anyone/23914) and then click [this link](http://www.cnet.com/products/samsung-sleepsense/). SmartThings plans to release SleepSense sometime in 2016. Too late for me but I think this would work as a "thing" that could trigger my morning routine scenario. I wouldn't buy this product however. I’m only interested in my high-level sleep patterns, so my [Shine](http://misfit.com/products/speedo-shine) works just fine for me. It looks like the SleepSense price will be around $200-$250. So this would be much too expensive if all I used it for is detecting when I woke up.

The forum article suggests that I could DIY something, but I’m not interested in that. 

It occurs to me now that my Shine tracks my sleep, and it knows when I’m "awake." So maybe it could trigger the morning routine scenario? Google "smartthings and misfit shine." Looks like SmartThings doesn’t support it. Maybe IFTTT? Bummer, the IFTTT triggers for Misfit don’t include "when I wake up."

After 15 more minutes of thinking and wandering in the product section, I decide that I could get a motion detector and put it on my nightstand. When I wake up and wave my hand over it, that action would trigger my morning routine scenario. If there is a better or more efficient way to do this, I no longer care. I’ve already spent 30 minutes on just one piece of hardware for my morning routine - this is taking way too long! 

Now I'm on the [motion sensor page](https://shop.smartthings.com/#!/products/samsung-smartthings-motion-sensor). The 2-pack is a slightly better deal (saves $4), so I'm wondering if I should do that. Spend some time thinking about how I would make the "know when mail arrives" scenario work. Will a motion sensor work? Or do I need an open/close sensor? Argh just want to finish this one scenario for now. So I put 1 motion sensor in my cart.

Now I need a way to control my kitchen lights and my coffee pot. Go to [Lights and Switches](https://shop.smartthings.com/#!/taxons/things/lights-and-switches). The [SmartOutlet](https://shop.smartthings.com/#!/products/samsung-smartthings-outlet) looks like it will work. $55 each, kinda pricey, doing all the lights in my house would be a big investment. 

I _think_ I could get 2 of [these](https://shop.smartthings.com/#!/products/ge-in-wall-outlet) instead of the SmartOutlets. But I'm not up for electrical work for this exercise. Add 2 SmartOutlets to my cart.

I can already tell that I'm going to hate how the SmartOutlet integrates into my old house with limited kitchen outlets. The undercounter lights plug into one of [these extension things](http://i.stack.imgur.com/Wkt44.jpg). So the SmartOutlet will sit on top of that. Bulky and unattractive. At least it’s white though.

Now the mailbox scenario. I want the arrival of the mail to play a song inside my house. I think an open/close sensor would work. Google "smartthings and mailbox." Find [this](https://blog.smartthings.com/stories/herding-cats-checking-mail/), which confirms that an open/close sensor would work. Add the [Multipurpose Sensor](https://shop.smartthings.com/#!/products/samsung-smartthings-multipurpose-sensor) to cart. Then change my mind because my mailbox doesn't close all the way. Delete multipurpose sensor and add second motion sensor to cart.

> Sidebar observation: the SmartThings website has become useless to me at this point. Google is the way I'm finding most information, and many of the links take me the SmartThings community forums. This is an ok experience. But SmartThings should really do a better job of integrating the marketing portion of the website with the community forums, where I suspect the answers for many (most?) consumers lie.

How can I make the motion sensor trigger music playing? Google "smartthings and speakers." Ugh, now I have to get into home music/theater. Why does home music/theater have to be so complex? It’s stupid. Anyway, my (crappy) Airplay speakers don’t work with SmartThings. Based on 5 minutes of googling, I _think_ there might be a way to make Airplay work, but it seems to require a lot more research and fiddling around with components and possibly third-party software or integrations. Not motivated to do that. 

I have been thinking about getting Sonos speakers, which do work with SmartThings. Also "get a NAS" has been on my to-do list for the past year. So if I get both, it looks like I can make SmartThings play music from the NAS through a Sonos speaker when the mail arrives. 

Both the NAS and speakers have to be white, because I hate how black equipment breaks up the visual flow in my house. I know this requirement limits my options, but it's important to me. 

45 minutes later, I’ve researched and found a white NAS and a (mostly) white Sonos speaker that, _in theory_, also works with my Samsung Smart TV. It’s not entirely clear that this speaker works well with my TV, but it would be ideal if the speaker played music and TV. So I’m willing to try it out...

My SmartThings cart now totals $266. That amount includes the 5% "sign up for emails" discount. 

> Sidebar observation: Almost all retailers I interact with offer 10% (some offer 15% or 20%) off the first order when you volunteer to receive their marketing spam, I mean, email updates. However I've heard that SmartThings is selling at close to cost, so perhaps they can't do better than 5% off. That's great for consumers who plan to keep buying SmartThings products. Yet also unfortunate for SmartThings, as the 5% discount reads as "cheap" relative to other retailers.

I would also be spending about $800 on the NAS and Sonos. So my grand total would be close to $1100 for two relatively simple home scenarios, one of which (morning routine) I imagine is a very common scenario.

It's important to note that I could not achieve my goals of playing music without making additional purchases. This is precisely how the cost of smart home tech adds up quickly for many people -- smart home systems don't always work with people’s existing equipment. If you don't want to buy new equipment that does work with the system, you can go the DIY route. But DIY complexity produces another "expensive" cost in terms of time and energy.

Ok, done for the day.
++++++++++++++++++++
### <a name="purchase"></a>Purchase

_Tuesday, Feb 16, 2016_ 
My cart is saved from my earlier work. So I go ahead and place the order. _Note:_ while going through the purchase process, everything looks fine, no indications that anything is wrong.

After placing the order, I immediately receive an email saying that the motion sensors are backordered, but no date is provided for when they'll be back in stock. Ok that's not terrible; I'll get the other items sooner, right? No, in contrast to most other retailers, SmartThings will only ship an order when all the items are in stock. Seriously disappointed after spending all this time to figure out what to buy.

I go back to the product detail page to see if I missed the "backordered" messaging.

<img width="1053" alt="st_motion_sensor" src="https://cloud.githubusercontent.com/assets/234670/13095486/d0fb2c8e-d4c6-11e5-9754-dd724e600fd2.png">

There is a small section indicating that the motion sensors are out of stock. Clicking the ? icon doesn't provide an ETA for when they'll be back in stock.

So I email SmartThings to cancel my order. To their credit, they reply immediately with a note saying my order has been cancelled and that the motion sensors should be back in stock next week. I visit HomeDepot.com, and all the items are in stock. Place my order with Home Depot -- my new SmartThings will be at my house in 3 days!
++++++++++++++++++++
### <a name="fun"></a>I want more fun!

_Tuesday, Feb 16, 2016_

I'm also looking into building an ambient light indicator that responds when the mail arrives. I'll link to that investigation from here.

**Comment by davidascher** [comment]
I love it.

**Comment by lime124** [comment]
@ezoehunt - I was doing a bit of research on my own this weekend and I'm reminded of your bit during your presentation about "bringing joy". It sounds like your research, much like my own, was totally joyless. It's WAY too much time spent doing research and trying to figure out how to make the damn thing that you almost want to give up before even purchasing the items!

I think you had this in an email or IRC but I totally agree that it would be awesome to see very simple scenarios and how to accomplish those. Any one of James's things (e.g. make coffee when motion detected) would have been plenty to get started. People are curious and I think once they get the hang of it there will be those who will naturally start to try to make it more complex.

**Comment by ezoehunt** [comment]
@lime124 Agree about the examples! It's pretty hard to look at any of these systems and see what's truly possible. I want a whole page loaded with small examples showing me the range, the breadth, of things I could do and, like you say, my imagination will take it from there. Another way to do it would be to package items together, e.g., the Morning Routine Kit - turns on 2 sets of lights and fires up your coffeepot. People would totally buy that kit. After you'd gotten that kit working, you'd probably start thinking of other things you'd want to do. 

Going into this experience, I was prepared to discover something new about SmartThings. But my earlier observation that they're about security, monitoring, and lighting remains steadfast. You may, in fact, be able to do much more with SmartThings. But they're not telling us that, and it takes a whole lot of time and effort to uncover that information...

**Comment by ezoehunt** [comment]
See [SmartThings makes me feel stupid](https://github.com/mozilla/connected-devices-experiments/issues/8) for the first installment of me setting up SmartThings in my home.
