### ISSUE TITLE
Endless notifications from SmartThing

### ISSUE THREAD

**Issue by Juwei-huang** [mozilla/connected-devices-experiments#10]
I installed SmartThing Motion sensor yesterday, and it sends me tons of notification in one night:
![image1](https://cloud.githubusercontent.com/assets/6365080/13241568/3302b928-da27-11e5-91ad-39217b6cff1d.PNG)
The notification will happen when:
- Temperature lower/up 1 degree
- Motion detected (time interval: minute)

I cannot see any details from the notification until I enter the app to see it's either temperature raise or motion movement detected...
I feel like I lost trust to the device since I received a lot of notifications yet still don't know what is really happen in my house.

**Comment by ezoehunt** [comment]
@Juwei-huang Thanks for posting this - great to see the visual of how annoying these notifications can be!

Does SmartThings let you create more sophisticated rules, so you only see notification for motion sensing if you're **not** in the house? I recently got mine and haven't been able to figure out how to make rules that work better for me...seems all or nothing...

**Comment by Juwei-huang** [comment]
Yes I think it's because I'm not around the sensor I set up... but it's also weird that sometimes I'll get notification but sometimes not even when I am around the sensor...
I setup the multipurpose sensor to detect whether harly is in office by detecting his drawer is open or closed (since he always put his briefcase in the drawer when in office). I found sometime it send me the notification sometimes not.
I believe the device probably has its own rules behind which I still cannot figure out yet...
