### ISSUE TITLE
Interoperability settings of smart devices

### ISSUE THREAD

**Issue by Juwei-huang** [mozilla/connected-devices-experiments#12]
Products I studied:
Samsung SmartThings: connect to Phillip hue
Amazon echo: connect to Philip hue
Wink: N/A (fail to connect to wink hub itself)
IFTTT app: connect to SmartThings, Phillip hue, Amazon echo
Stringify app: connect to SmartThings, Phillip hue, Amazon echo

Review:
**1. Connect different smart devices together: 3rd party Apps do better (so far)**
In general, 3rd party apps do better job than smart products.
When I try to connect Phillip hue to SmartThing & Amazon, it always encounter issues such as can’t find the hub, can’t find the device, etc. However, there’s less problem in 3rd party apps.

**2. Setting process is long, long, long**
When I use 3rd party app to connect smart devices, I need to log in every single devices I setup before, which can be very annoying.
If I use smart device to connect another smart device, the process even longer: I have to wait for the pairing process. It can seriously take a long time. 
For example, SmartThings would take more than 5 mins to connect to Phillip hue. And actually I haven’t connected them successfully yet ...
![img_7401](https://cloud.githubusercontent.com/assets/6365080/13349665/56fcbd2e-dcb6-11e5-9cfd-ef678a38862f.PNG)
And even for the simple "setting up the hub" flow, sometimes it takes longer...(10 hours...!?)
i.e. Wink hub:
![img_7387](https://cloud.githubusercontent.com/assets/6365080/13349720/98644cfa-dcb6-11e5-9658-5b7b290ff79b.PNG)

**3. Aware of "lagging"**
Although it’s easier to use 3rd party apps to connect different smart devices, I found that sometimes the action will “lag” for a few seconds.
For example, I use IFTTT to setup “When I say trigger red to Amazon Alexa, Phillip hue changes colour to red”. However, it takes 5 seconds delay when I trigger the action.

**Comment by lime124** [comment]
TEN HOURS?!?! Is it readying itself to control a space shuttle? I expect things to work out of the box and setup to be fast. I could return it to the store in less time.
