### ISSUE TITLE
A Independent Study of Smart Home Communications

### ISSUE THREAD

**Issue by kglazko** [mozilla/connected-devices-experiments#14]
[SmartHomeCommunicationResearchReport.pdf](https://github.com/mozilla/connected-devices-experiments/files/151932/SmartHomeCommunicationResearchReport.pdf)
<br/>
Feel free to take a look at this independently-run study that I did to better understand how people want to interact with their smart devices. 

For future research, I am mainly interested in generational and demographic differences in communication preference- how would Gen Z, who has grown up with smart phones and texting, prefer to communicate with devices? How do people who live alone prefer to communicate with them, in contrast to those with roommates or family?

**Comment by epang** [comment]
@yglazko Thanks for starting the research and exploration on this Kate!  I agree that voice being the most natural UI is a complex statement.  Especially with the way new generations are brought up.. You can already see it in most groups - even though they are surrounded by people most of them have their heads down looking at their devices (myself included).  You also brought up a great point about voicemail.. I do pretty much anything to avoid leaving messages - I much rather send text, msg on social media or email if I can't get through.

**Comment by KatieCaldwell** [comment]
@yglazko Thanks for sharing this! I love that you wanted to do some quick and dirty research to help answer some questions you had. We (UX team) also have a ton of questions in this space and we should work together and them answered! We also have access to researchers who have been a great resource and sounding board.
