### ISSUE TITLE
Particle.io review

### ISSUE THREAD

**Issue by sfoster** [mozilla/connected-devices-experiments#18]
IoT platform: dev board and services. They have docs and support for the full prototyping -> production project lifecycle. The "photon" board is built around ARM Cortex M3 micro-controller with a Broadcom Wi-Fi chip. Open source software including node.js libraries, cli, IDE etc. 

https://www.particle.io/
https://docs.particle.io/

**Comment by mikehenrty** [comment]
@sfoster, is this a review in progress, or is the above the entire content of the review?

**Comment by sfoster** [comment]
@mikehenrty nope, that was not the review :) I was hoping someone would dig a bit deeper and see how it stacked up against similar offerings on the hardware, software and services sides. As it happens we're ordering some Particle products for the next round of research on the smart home project so maybe that will be me afterall.
