### ISSUE TITLE
IBM Watson

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/connected-devices-experiments#24]
Let's make an experiment to investigate IBM Watson.

**Comment by etiennesegonzac** [comment]
IBM watson is a _vast_ service with tons of API, JS code sample etc... (nice illustration work too!)

So with some forking/mashup/getUserMedia goodness it should be pretty straightforward to build the following experiment:
- You're on a web page.
- You _say_ something.
- You get a ted talk related to what you said.
- Stretch goal, the web page _talks back to you_ if nothing related is found.

Sweet, simple, touches 3 different services and would be a cool TV use case.

Oh and they have a crazy cloud9-y dev platform so I might try to build all of this from a browser :)

**Comment by etiennesegonzac** [comment]
Here's where I'm at: https://cd-watson-experiment.eu-gb.mybluemix.net/

Assigned to the **magnet** train now so this issue is up for grab for the next few weeks at least.
Will assign myself again if/when I pick it up.
