### ISSUE TITLE
Alexa SDK

### ISSUE THREAD

**Issue by lime124** [mozilla/connected-devices-experiments#25]
Would someone be able to help me review/look into the Alexa SDK?

https://developer.amazon.com/appsandservices/solutions/alexa/alexa-skills-kit

**Comment by mikehenrty** [comment]
Hi Tif. What specifically would you like to investigate here? Ie. what's the use-case or rationale?

FYI, we have this spreadsheet (which we are going to move into the repo soon) which lists the technologies we currently plan to explore more, with their priority ranking:

https://docs.google.com/spreadsheets/d/1GHDeo-jWsCoeLsgIpiynJA0cDNv5T4T22KUMu-4-Yx4/edit#gid=0

**Comment by mikehenrty** [comment]
From Tif:

> I'm interested from a developer perspective the pain points, the difficulties, i.e. how to we do vaani better

It's now in the prioritization doc with a ranking of 1, so we will be investigating this soon.
