### ISSUE TITLE
wiolink

### ISSUE THREAD

**Issue by gasolin** [mozilla/connected-devices-experiments#28]
http://www.seeedstudio.com/wiki/Wio_Link

Just got my wiolink, `$12` board that have wide range of easy plug-able Grove sensors support
(Grove is sensor modules that can be easy plug and play, and used for Arduino, respberry Pi, beagleboard, MediaTek Linkit, Intel edison, and wiolink http://www.seeedstudio.com/wiki/Category:Grove)

I download the Android app https://play.google.com/store/apps/details?id=cc.seeed.iot.ap
- Setup wiolink wifi connection with its app < 1 minute
- Sign up and Login to wiolink account < 1 minute

Then the device is shown on app. 

add button and servo modules onto wiolink < 1minute
1 button to compile and update the firmware to device < 1minute

Then wiolink app shows the real `Web API` to me. I can test that API directly in app, and start building web service.

**Comment by gasolin** [comment]
It support IFTTT channel as well http://www.seeedstudio.com/recipe/1059-no-more-missed-calls-from-your-honey.html

**Comment by yshlin** [comment]
5 mins setup on your smartphone, no coding,
and you are able to control your module via RESTful API.
This is really cool. 

Currently they haven't release documentations to customize it's firmware.
But default firmware already supports a good variety of modules.
