### ISSUE TITLE
Amazon Echo Review

### ISSUE THREAD

**Issue by lime124** [mozilla/connected-devices-experiments#3]
**Unboxing**
https://search.yahoo.com/yhs/search;_ylt=AwrTcYNmdrFWr5gANg4unIlQ?p=amazon%20echo%20unboxing&fr=yhs-m ozilla-002&fr2=p%3As%2Cv%3Ai%2Cm%3Apivot&stype=web&hsimp=yhs-002&hspart=mozilla

I’ll admit it was WAY smaller than I had envisioned. I thought it was some sort of tall tower. It’s hard to say if that led me to feeling underwhelmed - like a “is this it” kind of feeling.

It was very simple - the device, the plug, a small start manual. This manual was exactly what I was missing from the Hello Sense even though it’s basically the exact same info - plug in the thing and go download the app.

I do dislike the giant black box the cord came in. I always feel compelled to go through everything to make sure I didn’t miss anything.

**Setup**

Per the manual, I plugged it in. I choose my living room mostly because it could be high out of Alexander’s reach that wasn’t the kitchen. I didn’t want to deal with it getting messy or having to move it to clean the counters.

Immediately after plugging it in it shows a moving circle of lights. The mic button is red and I’m unsure if it’s muted or not. I think it’s very cool that it has a mute button though. As I went back to the couch to then find my phone, it suddenly played music. Granted it started quiet and went louder but it still surprised me. Then Alexa started speaking - LOUDLY - and my dog and I both looked at it and then each other. I’m thinking god lord I hope that doesn’t wake up Alexander and wondering if it has a volume button.

Amazon also gives me a quick URL short to the app - cool. But I am getting a little tired of downloading an app for every...single...thing in my house. Nest, Sense, Fitbit and now Alexa. Could they not have at very least combined it with the Amazon app?

The app makes me sign in - they could have at least done the same thing Google does which is only make me sign in once. I have prime now and amazon on my phone. Why can’t it auto sign me in? And of course I have 2 factor auth so I have to do that as well.

The very first screen in the app setup wizard has a truncated title. I’m already skeptical of the app’s design. The odd bit of setup was I had to go to my Settings and select the Amazon wifi from my house wifi. It was strange and a little confusing. Alexa confirmed again in her booming voice. Given that I’m sitting right next to it it seems unnecessarily (and I need visual contact for setup). I think it made me connect to Alexa via Amazon wifi so that I could then enter in my real wifi settings and push that to her so she could connect to my home wifi herself. It like providing a way to set that up without a UI on the device itself. Either way, the waiting time of “preparing your echo” felt slow. Despite finishing the setup - Alexa is still yellow.

It’s now forcing me to watch a 3 min video. There is no skip button or do it later. The video was annoying, I really just want a list of stuff I can say that I can skim over and refer to later. After the video it has you try out some commands. I tired one but Alexa was red. No idea why. Finishing the intro I realize that Alexa is muted so I walk over to unmute. I asked for the weather and in a booming voice she replies. I try to shush her to no effect. I ask her if she could be quieter and she doesn’t reply.

**Usage**

After a weekend of use, I found that I mostly enjoyed listening to music while using a few of the other basic functions. Read on!

**Interaction and Feedback Loop**

My very first task was to figure out how to turn down the volume which actually took some googling. It wasn’t an easy thing to find, but there is a way to adjust the volume so she’s not so booming. [an aside - I later realized that the mini card - which I didn’t read -(see unboxing video in setup skip to 3min mark) does in fact tell you how to adjust the volume. <insert sheepish face here>]

The feedback varies from silence to I didn’t understand that to I’m not able to find that. The silence one is especially annoying because it’s unclear if she just didn’t hear or if she’s purposefully ignoring me b/c I’ve already asked three things in a row that she couldn’t answer.

I’ve been surprised that I can generally rattle things off and she accurately hears it before one would think she’s actually listening. Instead of - “Alexa……..what time is it” I would say “Alexa what time is it?’ and get the answer.

**Is she a person?**

It feels kind of weird to just shout out commands all the time without any sort of gratitude or politeness. Perhaps I’m extra attentive b/c of my child, but I think not. It just feels wrong to shout out “Alexa play music” and not at least tack on a please at the end. Along those same lines I’ve noticed I have a tendency to say “Alexa can you play classical music please” instead of a command. This generally works but when Carl said “Alex can you play music” we got a literal interpretation of “can” when she listed the types of services she could connect to rather than playing music.

**What can she do?**

What time is it? Worked as expected

What is the weather? Knew where I am located and rattled off the weather. But she wasn’t able to do anything more sophisticated like “when will it rain next”, “will it rain today” (this is PDX after all!)

Music - she can do all the basic things you would expect like changing volume playing and stopping. She can play genres. She can also tell about who is currently playing. Since most of our usage has been around music, we quickly found many ‘use cases” not supported:
play more music by this artist
how much is this album to purchase
what is the next song
play music for a mood

It would be awesome if I could hook it up to Spotify or Google Play, but even so just being able to play NPR or a radio station easily was pretty awesome. You could say “play classical” and away you go. You can also adjust the volume via voice as well. I think we had something playing for most of the weekend.

To-do List

I also enjoyed adding tasks to my list. I used IFTTT to hook up the Echo’s to-do list with my inbox. Pretty useful! I did notice there was quite a bit of lag though (no idea who’s fault that would be). Also not awesome when my husband caught on and started adding things like “make me a sandwich” and “be nice to husband” to my list.

Reminders - I haven’t gotten super sophisticated with setting these yet. Basically said “set alarm for 6pm” kind of thing

General Information - It seems kind of random what she can and can’t answer. We’ve asked some things and she replied and others got the “i don’t understand the question” type reply. I found it strange that she could answer “what is the weather” with no location, but couldn’t answer “who is the governor” (though she could answer who is the governor of oregon - for the mayor, you had to use portland oregon and she called it the “political leader”).

Flash Brief

I said Flash Brief as Liz hinted that this was a feature I hadn’t heard of or tried yet. Alexa tuned into NPR and it sounds like it’s just the normal broadcast. 

Overall
It seems like she can do a lot of general basic tasks but when you want to get more complicated she totally breaks down. Sometimes she just focuses on a topic, e.g. weather, and just reiterates a the same reply for both “what is the weather” and “will it rain today?” I found it odd she was able to use location for some things e.g. weather and not others e.g governor.

**Sharing a Household**
Apparently you can share Alexa with other people in your household. 
https://www.amazon.com/gp/help/customer/display.html?nodeId=201628040
I followed the steps, but Carl was already in my household. I asked Alexa to switch accounts and she told me she couldn’t until Carl accepted the TOS. I asked Carl to do so and he asked me how. Of course my reply was “IDK - download the app.” The response was a grunt - i.e. I’ll do it later i.e. it’s not getting done.

Reading about it, it seems like it keeps content separate and you have to do things like “switch account” and “what account am i using”. 

Sidebar - imPo this seems ridiculous - who the F cares - and greatly speaks to the need for having a household account which people can then share stuff to (or not). A household cart that whoever cares would manage and approve purchases. If I could have my family add stuff to the cart - dog treats, TP, soap. It would be so easy to skim and approve - it could even be an email that shows up in the AM and you approve yesterday’s items. If you see your kid added 5 books - you could veto them or even save for later or add them to their wishlist. 

**-----Updates-----**
Feb 4 - In casual conversation last night, Carl used Alexa’s name. She interrupted our conversation with a “I’m sorry I didn’t understand that”. We both paused and looked at each other. That was strange. It’s kind of like that guest at a dinner party who randomly injects into a conversation in a really awkward way that makes no sense. There’s a subtlety that she doesn’t understand - when her name is being used to refer to her vs talking to her.

**Comment by lime124** [comment]
Another update...

I've moved the Echo into the office. After a few days, someone in the office privately pulled me aside and asked if we could change the wake word from Alexa. The reason - "listening to men order a 'woman' around all, some of which are very rude about it, has become grating."

I thought that was very interesting and relevant for Vaani.

Another item I wanted to note which is issues with contextual volume. When I'm in the same room, I want a lower volume than when I'm in a different room. I've run into issues where I've asked something from the kitchen and then couldn't hear the response. Or it was way too loud and startled me.

**Comment by ezoehunt** [comment]
Ohhh...that's interesting about response to Alexa's name. Can you change the name?
