### ISSUE TITLE
registering a beacon with the Beacon Tools App

### ISSUE THREAD

**Issue by ptran78** [mozilla/connected-devices-experiments#33]
Hi,

I am struggle for registering my RadBeacon Dot with the Beacon Tools app to broadcast Eddystone UID through Nearby Notifications. It seems like this tool can't detect my nearby beacon. Can someone please help?

Thanks!

**Comment by sfoster** [comment]
I'm afraid I know nothing about the Beacon Tools app, or the RadBeacon Dot. This repo is not current, and probably not the right forum for this question.
