### ISSUE TITLE
Belkin WeMo Switch Review

### ISSUE THREAD

**Issue by rwood-moz** [mozilla/connected-devices-experiments#5]
**Belkin WeMo Switch**

As part of our IOT research I decided to try out the WeMo Switch from Belkin. The WeMo switch plugs into any power outlet, and provides one single power outlet that can be controlled via WiFi. This is the switch that I purchased: http://www.belkin.com/us/F7C027-Belkin/p/P-F7C027/

**Cost**

For a small piece of technology it is relatively expensive. A single WeMo power switch here in Canada costs $49.99. There is a smaller more attractive model, the WeMo insight, but that costs even more ($59.99 in Canada).

**Setup**

Initial setup was really easy and only took a few minutes, using the following steps:
- Downloaded the WeMo iOS app
- Unboxed the WeMo switch, plugged it into a power outlet
- On my iPhone, went into WiFi settings and searched for the WiFi hotpsot that my WeMo switch had created itself; connected to the WeMo switch's WiFi
- Started the WeMo app, selected my WeMo switch and configured it by naming the switch, and telling the switch which WiFi network I wanted it to be a part of. Note: If you are on a secure WiFi network you need to also provide the password
- Exited the WeMo app. On my iPhone WiFi settings I connected to the same WiFi network that I told the WeMo switch to be a part of
- Started up the WeMo app again, this time the WeMo switch is shown with a power button beside it, and it is ready for use
- Attach whatever you want to run on the switch power outlet; in my case I plugged in a desk lamp and turned the lamp switch on

I thought it was really cool that the WeMo switch was ready to use right out of the box, and the best part was it didn't have to be registered online; I didn't need to create an account on the manufacturers cloud or anything; and I didn't have to provide any personal information besides the WiFi network info.

**Usage**

Just start the WeMo app and the switch appears in the list of you WeMo devices. Beside the switch (showing the name that you configured it with) there's a power button; tap the power button on the app and the switch power is turned on. Once turned on the switch icon turns green to indicate the power is on. Tap it again to turn it off and the button turns red. In my case, I could easily turn the lamp on my desk on and off with a tap of the button on the mobile app.

With the setup I used, my phone had to always be on the same WiFi network as the WeMo switch. Apparently there is a way to configure the switch so you can control it from anywhere on the internet and not just while you're on the same WiFi network, however I didn't try that out. Also the switch is compatible with [IFTTT](https://ifttt.com/) which means you can setup automation rules, like turning on the power switch at a certain time of day, or sending a text to control the switch, etc. I didn't try those features.

**Issues**

Generally the switch worked great however I did see the following issues now and then:
- The switch lost connectivity with the network; a couple of times I had to press the physical reset button on the switch in order for it to connect to the network again
- Sometimes there was a delay from when the switch button on the app was tapped and the switch power was actually turned on/off. Most times it was just a small delay hardly noticeable, but a couple of times it was a noticeable delay of a second or two

**Summary**

Cool product and easy to setup. I could see it being useful if you want to control one or two power outlets in your home; however due to cost I personally probably wouldn't invest in buying a large number of these devices.

**Comment by robmacd8** [comment]
Great summary. I use the Belkin WeMo switch and light bulbs remotely. Generally it works well but about 20% of the time it doesn't detect all the devices. I think this may be related to the range of wi-fi in the house because it tends to be the devices that are furthest away from the router.

That said, even when the device isn't detectable, it still operates on the schedule I originally applied. The lights turn on and off at the right time consistently even without the network connection... which gives me a bit more peace of mind.
